### ISSUE TITLE
Research algorithms and Past works

### ISSUE THREAD

**Issue by Hash2402** [Hash2402/CV_Project2-Part1#3]
## Description
This issue aims to gather insights and evaluations of relevant algorithms that could enhance our current project. The goal is to ensure that we are leveraging the most effective approaches and learning from previous research.

#### Algorithm Research:

- Investigate recent algorihtms for object detction , depth analysisand parabola tracking.

- Compare at least three different algorithms based on criteria such as efficiency, accuracy, and applicability to our project.

#### Review Past Work:

- Summarize key findings from existing research or projects related to our current work.

- Identify best practices and common pitfalls observed in previous implementations.

**Comment by JN720** [comment]
### Trajectory Calculation Algorithm
We can look into RANSAC to remove outliers from the parabola the projectile motion forms.
https://www.mathworks.com/discovery/ransac.html

### Detecting Misses
We can also detect if a shot is made by checking if there is a frame with a sufficiently high IoU between the bounding boxes of the hoop and the ball itself.
