### ISSUE TITLE
Ball Detection Task - Keras Tutorial and Dataset

### ISSUE THREAD

**Issue by Hash2402** [Hash2402/CV_Project2-Part1#4]
## Ball Detection Task - Working with Keras Tutorial and Dataset

#### Find and review Keras tutorial:

Locate a suitable tutorial for ball detection using Keras.
Ensure it aligns with the project requirements (e.g., object detection and tracking).
#### Dataset acquisition:

Identify and download the dataset used for training the ball detection model.
Verify the dataset’s compatibility with the tutorial.
#### Implementation:

Follow the tutorial to build the ball detection model using Keras.
Ensure the model is trained with the identified dataset.
Document any issues or deviations from the tutorial for future reference.
#### Testing:

Test the ball detection model on sample video footage to evaluate its performance.
Identify areas for improvement or further tuning.
#### Timeline:

Aim to have the implementation completed by 10/31/2024.

**Comment by Hash2402** [comment]
### Dataset 

I found this dataset on kaggle , I think it is pretty good .
Check this and let me know how it is

https://www.kaggle.com/datasets/gabrielvanzandycke/deepsport-dataset

**Comment by JN720** [comment]
Overall it doesn't seem bad but it looks like it has keypoint coordintes instead of bounding boxes. I found this one with over 2k images and bounding boxes on Roboflow: https://universe.roboflow.com/eagle-eye/basketball-1zhpe/dataset/1.
Maybe we can try that one instead? Worst case, we can try to adapt the keypoint-style dataset to work.

**Comment by jaskaran1920** [comment]
I found a dataset on Kaggle, I think we ca use this also.
[https://www.kaggle.com/datasets/wyattowalsh/basketball?select=csv](url)

**Comment by JN720** [comment]
I committed an initial draft of the model training notebook based on the keras tutorial we found. However, I think there's a problem with the bounding box data loading. Could any of you check to see what the issue might be?
