### ISSUE TITLE
Fix Initial Draft of Ball Detection Model

### ISSUE THREAD

**Issue by JN720** [Hash2402/CV_Project2-Part1#7]
The model seems to be detecting the bounding boxes incorrectly. I checked the ground truth images and they also seem to be incorrectly shown and do not actually display a box around the basketball. I believe this is likely an issue with how the bounding boxes are being loaded. It might be possible that I am not using the format correctly, could one of you look into this?
![image](https://github.com/user-attachments/assets/87bfc372-4570-4dc0-9a7b-c0302ba0e5cc)
That is an example of what the problem looks like.

**Comment by jaskaran1920** [comment]
https://colab.research.google.com/drive/1PxoFXCJSNfFRV2SeWbHXV4K63KGC2Grw?usp=sharing
